#워크 플로우 이름 지정
name: Main_Workflows

##워크 플로우의 특징 정의
#on:
#  push:
#    branches: #main brach 대상으로 push 이벤트가 발생하면 job이 수행 됨.
#      - main

##pr 생성 또는 업데이트 main -> 다른 브랜치
#on:
#  pull_request:
#    branches:
#      - develop

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        default: 'staging'

#jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "pr test main -> develop"