#워크 플로우 이름 지정
name: Main_Workflows

#워크 플로우의 특징 정의
on:
  push:
    branches:
      - main

#jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "pr test"